language: python
python:
- '3.4'

node_js:
- 0.10.13

ruby:
- 1.9.3-p429

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm

install:
- pip install -qr requirements.txt
- pip install -qr requirements-dev.txt
- ./install_assets_deps.sh
- grunt clean build

script:
- nosetests -c nose.cfg --verbosity=1
- grunt test

